// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nigacoophkwyeobmpaik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pZ2Fjb29waGt3eWVvYm1wYWlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3ODQ0NjQsImV4cCI6MjA2ODM2MDQ2NH0.v7_73Fl3H7vGAE2nheyOGPJtp6LyWhbQ1MFToB0K-8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});